### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by JakeWhitaker** [arghblargh/feh-inheritance-tool#25]
1: Skill called Affinity Breaker in the B Slot doesn't exist

2: Special Fighter Available on non-armour characters

3: Sothe missing 4-star lv.40 and 4-star lv.1 

4: Blizzard inheritable, it's Gunnthra's Prf 

5: All swords, even Prfs, inheritable by Athena

**Comment by arghblargh** [comment]
That's a lot of bugs! Thanks!

**Comment by JakeWhitaker** [comment]
No problem! Love your resource. I use it all the time.
________________________________
