### ISSUE TITLE
Seems like something is off with Boons/Banes calc

### ISSUE THREAD

**Issue by JakeWhitaker** [arghblargh/feh-inheritance-tool#31]
I've noticed on both Seth and normal Eirika, when calculating at +10, putting a Boon on will decrease other stats

**Comment by arghblargh** [comment]
This should be correct based on the new merge bonuses.
Neutral units get +1 in 3 stats, while units with boon/bane have the bane negated.

**Comment by JakeWhitaker** [comment]
You're right, my mistake. Was weird to see. Thanks!
