### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by JakeWhitaker** [arghblargh/feh-inheritance-tool#32]
Flame Siegmund has a refinement option for both an "x" skill that breaks the page, and a/s/d/r which don't exist.

For some units, skills they can't inherit aren't listed, like offensive specials for healers for example. Others are listed even if they're inherit restricted. Here's a list of errors I've noticed, things inheritable when they shouldn't be:

    Breath(Fierce, Steady, Warding) inheritable by all Cavalry, Fliers, Ranged Units
    Sturdy Impact inheritable by Armours and Cavalry
    Steady Stance 4 inheritable by Healers(3 can be given to healers, 4 cannot)
    Null C-Disrupt and Null-Follow Up inheritable by Armours, Cavalry, and Fliers
    Dull Close inheritable by Ranged Units
    Smoke Skills inheritable by Healers

I've noticed some skills, like Blarserpent, have their Gronn and Rauor equivalents already added, even though we don't have access to them yet, but others like Joint Hone Spd don't have their equivalents. Not sure if intentional or not, just figured I'd mention it

**Comment by arghblargh** [comment]
Thanks for the list. I haven't actually updated the skill restrictions in a while, so this helps a lot.

The skill thing was also something I added on a whim, so I didn't add everything.
